sudo: false
language: c
compiler:
 - gcc
 - clang
addons:
  apt:
    packages:
      - libjansson-dev
before_install:
 - git clean -x -f
 - ./autogen.sh
script:
 - ./configure
 - make -j8
 - make check -j8
notifications:
    email: false
